import Html exposing (..)
import Html.Attributes exposing (..)


main =
  section [ class "todoapp" ]
    [ header [ class "header" ]
      [ h1 []
        [ text "todos" ]
      , input [ class "new-todo", placeholder "What needs to be done?" ]
        []
      ]
    , section [ class "main", attribute "style" "display: block;" ]
      [ input [ class "toggle-all", id "toggle-all", type' "checkbox" ]
        []
      , label [ for "toggle-all" ]
        [ text "Mark all as complete" ]
      , ul [ class "todo-list" ]
        [ li [ class "completed" ]
          [ div [ class "view" ]
            [ input [ checked False, class "toggle", type' "checkbox" ]
              []
            , label []
              [ text "Walk the dogs" ]
            , button [ class "destroy" ]
              []
            ]
          , input [ class "edit", value "Walk the dogs" ]
            []
          ]
        , li []
          [ div [ class "view" ]
            [ input [ class "toggle", type' "checkbox" ]
              []
            , label []
              [ text "kill rats" ]
            , button [ class "destroy" ]
              []
            ]
          , input [ class "edit", value "kill rats" ]
            []
          ]
        , li []
          [ div [ class "view" ]
            [ input [ class "toggle", type' "checkbox" ]
              []
            , label []
              [ text "laundry" ]
            , button [ class "destroy" ]
              []
            ]
          , input [ class "edit", value "laundry" ]
            []
          ]
        , li []
          [ div [ class "view" ]
            [ input [ class "toggle", type' "checkbox" ]
              []
            , label []
              [ text "new leg for suby" ]
            , button [ class "destroy" ]
              []
            ]
          , input [ class "edit", value "new leg for suby" ]
            []
          ]
        ]
      ]
    , footer [ class "footer", attribute "style" "display: block;" ]
      [ span [ class "todo-count" ]
        [ strong []
          [ text "3" ]
        , text "items left"
        ]
      , ul [ class "filters" ]
        [ li []
          [ a [ class "selected", href "#/" ]
            [ text "All" ]
          ]
        , li []
          [ a [ href "#/active" ]
            [ text "Active" ]
          ]
        , li []
          [ a [ href "#/completed" ]
            [ text "Completed" ]
          ]
        ]
      , button [ class "clear-completed" ]
        [ text "Clear completed" ]
      ]
    ]
